"""Dummy-controlled model selection for high-dimensional Gaussian graph learning.

This package implements the two selection procedures studied in

    H. Mehler, T. Koka, M. Muma, "Dummy-Controlled Model Selection for
    High-Dimensional Gaussian Graph Learning", EUSIPCO 2026.

* :class:`~dummy_ggm.lars.TLarsNodewise` -- dummy-augmented neighborhood
  selection (NS), one forward-selection regression per node.
* :class:`~dummy_ggm.graph_lars.TLarsGraph` -- the global,
  symmetry-constrained pseudo-likelihood (SCPL) formulation that performs
  forward selection directly at the level of undirected edges.

Synthetic Gaussian graphical models with known ground truth are generated by
:mod:`dummy_ggm.graphs`.
"""

from dummy_ggm.graph_tlars import TLarsGraph, index_to_edge, init_index_to_edge
from dummy_ggm.graph_generators import (
    generate_er_graph,
    generate_pa_graph,
    generate_small_world_graph,
)
from dummy_ggm.tlars import TLarsNodewise

__all__ = [
    "TLarsNodewise",
    "TLarsGraph",
    "init_index_to_edge",
    "index_to_edge",
    "generate_er_graph",
    "generate_pa_graph",
    "generate_small_world_graph",
]

__version__ = "0.1.0"
